repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        always_run: true
      - id: trailing-whitespace
        always_run: true
        exclude: ^(docs/|.+\.md|.bumpversion.cfg)
      - id: check-docstring-first
        always_run: true
        exclude: ^(packages/grid/ansible/)
      - id: check-added-large-files
        always_run: true
      - id: check-yaml
        always_run: true
      - id: check-merge-conflict
        always_run: true
        args: ["--assume-in-merge"]
      - id: check-executables-have-shebangs
        always_run: true
      - id: debug-statements
        always_run: true
      - id: name-tests-test
        always_run: true
      - id: requirements-txt-fixer
        always_run: true
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: '\.bat|\.csv|\.ps1$'

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: ["--never", "--application-directories=src"]
        always_run: true
        files: ^src

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["."]
        always_run: true

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [".", "--settings-path .isort.cfg"]
        always_run: true




  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: ["." ] # add  config later"--config=packages/syft/setup.cfg"]
  #       always_run: true
  #       additional_dependencies:
  #         - flake8-bugbear
  #Add flake8 with config files

# add mypy later