auth:
- auth_name: pkipsk
  auth_type: signed_headers
base_image: oblv_ubuntu_18_04_proxy_nsm_api_python_3_9
build_args: []
meta:
  author: Team Oblivious
  author_email: hello@oblivious.ai
  git: https://github.com/ObliviousAI/FastAPI-Enclave-Services.git
  version: 0.1.0
paths:
- access: domain,user
  path: /api/v1/new/api
  short_description: contains worker api metadata
- access: domain,user
  path: /api/v1/new/api_call
  short_description: Syft API endpoint
roles:
- role_auth: pkipsk
  role_cardinality: 3
  role_description: Role for the domain nodes
  role_name: domain
- role_auth: pkipsk
  role_cardinality: 1
  role_description: Role for the data scientist
  role_name: user

traffic:
  inbound:
  - name: inbound
    port: 80
    type: tcp
  outbound: []
